import { spawn } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import type { HudSettings } from "@cs2hud/shared";
import { env } from "../config/env.js";

export const SYNC_CFG_FILENAME = "sync.cfg";

type HlaeToggles = Pick<
  HudSettings,
  "hlaeKillfeedEnabled" | "hlaeXrayEnabled" | "hlaeTrailsEnabled" | "hlaeAboveHeadInfoEnabled" | "hlaeSmokesEnabled"
>;
type Colors = { ctColor: string; tColor: string };

function hexToRgb(hex: string): [number, number, number] {
  const clean = hex.replace("#", "");
  return [parseInt(clean.slice(0, 2), 16) || 0, parseInt(clean.slice(2, 4), 16) || 0, parseInt(clean.slice(4, 6), 16) || 0];
}

/**
 * Generates sync.cfg: CS2/HLAE console commands that color the killfeed,
 * X-ray glow, grenade trails, above-head team info, and smoke color from
 * the configured CT/T colors. Command syntax verified against the official
 * advancedfx wiki (2026-08-01):
 *  - https://github.com/advancedfx/advancedfx/wiki/Source2:mirv_colors
 *  - https://github.com/advancedfx/advancedfx/wiki/Source2:mirv_deathmsg
 * The user runs `exec sync` in the CS2 console to apply it — the filename
 * has to be exactly "sync.cfg" for that to work.
 */
export function generateSyncCfg(colors: Colors, toggles: HlaeToggles): string {
  const [ctR, ctG, ctB] = hexToRgb(colors.ctColor);
  const [tR, tG, tB] = hexToRgb(colors.tColor);
  const lines: string[] = [
    `// Generated by CS2 HUD Tool.`,
    `// Re-run "exec sync" in the CS2 console after changing colors or these toggles.`,
  ];

  if (toggles.hlaeKillfeedEnabled) {
    lines.push(`mirv_deathmsg colors ct ${ctR} ${ctG} ${ctB} 255`, `mirv_deathmsg colors t ${tR} ${tG} ${tB} 255`);
  }
  if (toggles.hlaeXrayEnabled) {
    lines.push(`mirv_colors glow ct ${ctR} ${ctG} ${ctB} 255`, `mirv_colors glow t ${tR} ${tG} ${tB} 255`);
  }
  if (toggles.hlaeTrailsEnabled) {
    lines.push(`mirv_colors trails ct ${ctR} ${ctG} ${ctB} 255`, `mirv_colors trails t ${tR} ${tG} ${tB} 255`);
  }
  if (toggles.hlaeAboveHeadInfoEnabled) {
    lines.push(`mirv_colors teamid ct ${ctR} ${ctG} ${ctB} 255`, `mirv_colors teamid t ${tR} ${tG} ${tB} 255`);
  }
  if (toggles.hlaeSmokesEnabled) {
    // mirv_colors smokes only takes RGB, no alpha channel.
    lines.push(`mirv_colors smokes ct ${ctR} ${ctG} ${ctB}`, `mirv_colors smokes t ${tR} ${tG} ${tB}`);
  }

  return lines.join("\n") + "\n";
}

export function writeSyncCfg(content: string): { path: string } {
  if (!env.cs2CfgDir) {
    throw new Error("CS2_CFG_DIR is not set. Point it at your CS2 install's game/csgo/cfg folder (see .env.example).");
  }
  const targetPath = path.join(env.cs2CfgDir, SYNC_CFG_FILENAME);
  fs.writeFileSync(targetPath, content, "utf-8");
  return { path: targetPath };
}

/**
 * Opens HLAE.exe (its own GUI). There's no reliably documented HLAE
 * command line for fully unattended CS2 launches — the confirmed path is
 * HLAE's own "File → Launch CS2" menu, pointing at
 * <CS2 install>\game\bin\win64\cs2.exe with launch options
 * "-steam -insecure +sv_lan 1 -console -sw -w 1920 -h 1080 -afxDisableSteamStorage"
 * (per https://doc.hlae.site/guides/command_line_interfaces). We don't
 * download/install HLAE ourselves — get it from https://www.hlae.online/.
 */
export function launchHlae(): void {
  if (!env.hlaeExePath) {
    throw new Error("HLAE_EXE_PATH is not set. Download HLAE from https://www.hlae.online/ and point HLAE_EXE_PATH at HLAE.exe.");
  }
  if (!fs.existsSync(env.hlaeExePath)) {
    throw new Error(`HLAE_EXE_PATH points to a file that doesn't exist: ${env.hlaeExePath}`);
  }
  const child = spawn(env.hlaeExePath, [], { detached: true, stdio: "ignore", cwd: path.dirname(env.hlaeExePath) });
  child.unref();
}
