import fs from "node:fs";
import path from "node:path";
import type { CinematicCameraShot, CinematicMapCameras } from "@cs2hud/shared";
import { env } from "../config/env.js";

export const CINEMATIC_CFG_FILENAME = "cinematic.cfg";

function fmt(shot: CinematicCameraShot): string {
  return `${shot.x} ${shot.y} ${shot.z} ${shot.pitch} ${shot.yaw}`;
}

/**
 * Generates cinematic.cfg — binds `cinematic_ct` / `cinematic_t` aliases
 * that jump the free spectator camera to the shots captured for this map.
 * Command syntax (spec_mode 6 for free-roam + spec_goto X Y Z PITCH YAW)
 * confirmed against community command references (2026-08-01) — there's
 * no way to verify the actual x/y/z/pitch/yaw *values* without being in
 * the map, so those always come from the user's own `spec_pos` capture,
 * never guessed here.
 */
export function generateCinematicCfg(cameras: CinematicMapCameras): string {
  const lines = [`// Generated by CS2 Observer Toolkit for ${cameras.mapName}.`];
  if (cameras.ctShot) {
    lines.push(`alias cinematic_ct "spec_mode 6; spec_goto ${fmt(cameras.ctShot)}"`);
  } else {
    lines.push(`// No CT shot captured for ${cameras.mapName} yet.`);
  }
  if (cameras.tShot) {
    lines.push(`alias cinematic_t "spec_mode 6; spec_goto ${fmt(cameras.tShot)}"`);
  } else {
    lines.push(`// No T shot captured for ${cameras.mapName} yet.`);
  }
  return lines.join("\n") + "\n";
}

export function writeCinematicCfg(cameras: CinematicMapCameras): { path: string } {
  if (!env.cs2CfgDir) {
    throw new Error("CS2_CFG_DIR is not set. Point it at your CS2 install's game/csgo/cfg folder (see .env.example).");
  }
  const targetPath = path.join(env.cs2CfgDir, CINEMATIC_CFG_FILENAME);
  fs.writeFileSync(targetPath, generateCinematicCfg(cameras), "utf-8");
  return { path: targetPath };
}
