import fs from "node:fs";
import path from "node:path";
import type { CinematicShot } from "@cs2hud/shared";
import { readHudSettings } from "../db/hud-settings-store.js";
import { campathFilePath } from "./campath-storage.js";

export const CINEMATIC_CFG_FILENAME = "cinematic.cfg";

function slugify(label: string): string {
  return label.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "") || "shot";
}

/** Short, stable, alias-safe suffix so two shots with the same label don't collide. */
export function aliasName(shot: CinematicShot): string {
  return `cinematic_${slugify(shot.label)}_${shot.id.slice(0, 8)}`;
}

/**
 * The command that plays a shot: load its camera path and enable it (see
 * @cs2hud/shared's CinematicShot doc comment — every shot has one, there's
 * no static-jump fallback). `mirv_campath load`/`edit start`/`enabled`
 * syntax confirmed against the raw doc source (advancedfx/afx-doc,
 * docs/commands/AfxHookSource/mirv_campath.md — doc.hlae.site's *rendered*
 * page hides this behind prose with no visible command, which is why an
 * earlier version of this comment had the wrong name here) — the enable
 * subcommand is `enabled`, not `enable` (also verified against
 * papesgit/hot, a production HLAE observing tool, which sends the same
 * `mirv_campath enabled 1/0`). An absolute path is used (rather than
 * relying on CS2's cwd) since the file lives in this app's own storage,
 * not next to cs2.exe.
 *
 * `edit start` is required in between: a campath's keyframes carry an
 * *absolute* curtime (whatever the game clock read when each point was
 * recorded — e.g. 512s into that original session), and playback only
 * happens once the current clock actually reaches those timestamps.
 * Without re-anchoring, `enabled 1` silently does nothing in a fresh
 * session whose clock is nowhere near the recorded range — no error, the
 * camera just never moves. `mirv_campath edit start` ("Setting the path to
 * start at a new time" in the docs) shifts every keyframe so the path
 * starts playing right now instead.
 *
 * The leading `mirv_campath enabled 0` disables whatever path was already
 * playing (harmless no-op if none was) *before* `load` swaps out its
 * keyframe data — cutting straight from one freezetime shot to the next
 * (see cinematic/scheduler.ts) calls this back-to-back with the previous
 * path still mid-motion and still enabled, and loading new keyframe data
 * out from under an active path is what caused the brief flash of a stale
 * camera position between the two shots.
 */
export function shotCommand(shot: CinematicShot): string {
  return `mirv_campath enabled 0; spec_mode 6; mirv_campath load "${campathFilePath(shot.campathFileName)}"; mirv_campath edit start; mirv_campath enabled 1`;
}

/**
 * Generates cinematic.cfg — one `cinematic_<label>_<id>` alias per captured
 * shot for this map, loading and playing its camera path. This is a
 * manual-keybind fallback only — the primary trigger path is automatic,
 * over netconsole (see cinematic/scheduler.ts), which sends shotCommand's
 * output directly with no outer quoting, so the campath file path is never
 * at risk of the quote-escaping below.
 */
export function generateCinematicCfg(mapName: string, shots: CinematicShot[]): string {
  const lines = [`// Generated by CS2 Observer Toolkit for ${mapName}.`];
  if (shots.length === 0) {
    lines.push(`// No shots captured for ${mapName} yet.`);
  }
  for (const shot of shots) {
    // The whole command has to be wrapped in one quoted alias body, so the
    // embedded mirv_campath file path (itself quoted) needs its quotes
    // escaped to avoid terminating the alias body early.
    const command = shotCommand(shot).replace(/"/g, '\\"');
    lines.push(`alias ${aliasName(shot)} "${command}" // ${shot.label} (${shot.slot})`);
  }
  return lines.join("\n") + "\n";
}

export function writeCinematicCfg(mapName: string, shots: CinematicShot[]): { path: string } {
  const { cs2CfgDir } = readHudSettings();
  if (!cs2CfgDir) {
    throw new Error("CS2 cfg folder is not set. Set it on the GSI Setup page.");
  }
  const targetPath = path.join(cs2CfgDir, CINEMATIC_CFG_FILENAME);
  fs.writeFileSync(targetPath, generateCinematicCfg(mapName, shots), "utf-8");
  return { path: targetPath };
}
