import fs from "node:fs";
import path from "node:path";
import type { CinematicShot } from "@cs2hud/shared";
import { readHudSettings } from "../db/hud-settings-store.js";

export const CINEMATIC_CFG_FILENAME = "cinematic.cfg";

function slugify(label: string): string {
  return label.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "") || "shot";
}

/** Short, stable, alias-safe suffix so two shots with the same label don't collide. */
export function aliasName(shot: CinematicShot): string {
  return `cinematic_${slugify(shot.label)}_${shot.id.slice(0, 8)}`;
}

/**
 * Generates cinematic.cfg — one `cinematic_<label>_<id>` alias per captured
 * shot for this map, jumping the free spectator camera to it. Command
 * syntax (spec_mode 6 for free-roam + spec_goto X Y Z PITCH YAW) confirmed
 * against community command references — there's no way to verify the
 * actual x/y/z/pitch/yaw *values* without being in the map, so those
 * always come from the user's own `spec_pos` capture, never guessed here.
 * This is a manual-keybind fallback only — the primary trigger path is
 * automatic, over netconsole (see cinematic/scheduler.ts).
 */
export function generateCinematicCfg(mapName: string, shots: CinematicShot[]): string {
  const lines = [`// Generated by CS2 Observer Toolkit for ${mapName}.`];
  if (shots.length === 0) {
    lines.push(`// No shots captured for ${mapName} yet.`);
  }
  for (const shot of shots) {
    const { x, y, z, pitch, yaw } = shot.shot;
    lines.push(`alias ${aliasName(shot)} "spec_mode 6; spec_goto ${x} ${y} ${z} ${pitch} ${yaw}" // ${shot.label} (${shot.slot})`);
  }
  return lines.join("\n") + "\n";
}

export function writeCinematicCfg(mapName: string, shots: CinematicShot[]): { path: string } {
  const { cs2CfgDir } = readHudSettings();
  if (!cs2CfgDir) {
    throw new Error("CS2 cfg folder is not set. Set it on the GSI Setup page.");
  }
  const targetPath = path.join(cs2CfgDir, CINEMATIC_CFG_FILENAME);
  fs.writeFileSync(targetPath, generateCinematicCfg(mapName, shots), "utf-8");
  return { path: targetPath };
}
